function FFR_exp01_analysis(SID)
%% DESCRIPTION
%
% INPUT
%
% OUTPUT
%
% Bishop, Christopher W.
% University of Washington, 2013

%% DEFAULT VARIABLES

%% DETERMINE PSYCHOMETRIC RANGE

%% HIT RATE FOR EACH PARAMETER VALUE

%% FALSE ALARM RATE FOR EACH PARAMETER VALUE

%% D-PRIME MEASURE

%% PLOT RESULTS